### ISSUE TITLE
Need Requirement

### ISSUE THREAD

**Issue by qq625924821** [sporsho/3D_OutDet#1]
Hello, Could you provide the requirement for me? And tell me the version of python. I want to use your code for filtering snow! Thanck you very much!

**Comment by sporsho** [comment]
Hi, 
You can use this file as a requirement file. If conda fails to install all the libraries, use pip to install the missing libraries. https://github.com/sporsho/3D_OutDet/blob/main/wads_8_sep_2023.yml


Alternatively, you can also use the below shell script to create the environment. This is a minimal environment, not all the functionalities may be available with it. You can also update the script with any compatible library versions. 
```
#! /bin/bash 
echo "Conda version: "
conda -V 
echo "Attempting to update conda"
yes | conda update conda

echo "Creating environment"
yes | conda create -n outdet python=3.10
if [ $? -eq 0 ]; then
	echo "basic invironment installed"
	echo "Assuming you are using Bash"
	BASE=$(conda info --base)
	source $BASE/etc/profile.d/conda.sh
	conda activate outdet 
	pip config set global.extra-index-url https://pypi.ngc.nvidia.com
	yes | conda install numpy=1.23.1
	yes | conda install cudatoolkit=11.3.1
	yes | conda install pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0 -c pytorch
	yes | pip install pyyaml==6.0
	yes | pip install tqdm==4.46.1
	yes | pip install scikit-image==0.19.3
	yes | pip install scikit-learn==1.1.2
	yes | pip install scipy==1.9.1
	yes | pip install matplotlib==3.6.0
	yes | pip install cubinlinker-cu11==0.3.0.post1 --extra-index-url https://pypi.nvidia.com
	yes | pip install cuda-python==11.8.1
	yes | pip install cudf-cu11==23.6.0 --extra-index-url https://pypi.nvidia.com
	yes | pip install cuml-cu11==23.6.0 --extra-index-url https://pypi.nvidia.com
	yes | pip install cupy-cuda11x==12.1.0 
	yes | pip install torch-cluster==1.6.0
	which python 
	conda deactivate
else	
	echo "environment installation failed"
fi
```

**Comment by qq625924821** [comment]
thank you very much!



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 22, 2024 16:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sporsho/3D_OutDet] Need Requirement (Issue #1)




 
Hi,
 You can use this file as a requirement file. If conda fails to install all the libraries, use pip to install the missing libraries. https://github.com/sporsho/3D_OutDet/blob/main/wads_8_sep_2023.yml
 
Alternatively, you can also use the below shell script to create the environment. This is a minimal environment, not all the functionalities may be available with it. You can also update the script with any compatible library versions.
 #! /bin/bash  echo "Conda version: " conda -V  echo "Attempting to update conda" yes | conda update conda echo "Creating environment" yes | conda create -n outdet python=3.10 if [ $? -eq 0 ]; then 	echo "basic invironment installed" 	echo "Assuming you are using Bash" 	BASE=$(conda info --base) 	source $BASE/etc/profile.d/conda.sh 	conda activate outdet  	pip config set global.extra-index-url https://pypi.ngc.nvidia.com 	yes | conda install numpy=1.23.1 	yes | conda install cudatoolkit=11.3.1 	yes | conda install pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0 -c pytorch 	yes | pip install pyyaml==6.0 	yes | pip install tqdm==4.46.1 	yes | pip install scikit-image==0.19.3 	yes | pip install scikit-learn==1.1.2 	yes | pip install scipy==1.9.1 	yes | pip install matplotlib==3.6.0 	yes | pip install cubinlinker-cu11==0.3.0.post1 --extra-index-url https://pypi.nvidia.com 	yes | pip install cuda-python==11.8.1 	yes | pip install cudf-cu11==23.6.0 --extra-index-url https://pypi.nvidia.com 	yes | pip install cuml-cu11==23.6.0 --extra-index-url https://pypi.nvidia.com 	yes | pip install cupy-cuda11x==12.1.0  	yes | pip install torch-cluster==1.6.0 	which python  	conda deactivate else	 	echo "environment installation failed" fi

**Comment by qq625924821** [comment]
Hi, there are three pt models in the 3D_OutDet project, such as kitti、spray、wads. Can these models be used with each other?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sporsho/3D_OutDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sporsho/3D_OutDet] Need Requirement (Issue #1)





 
Hi,
 You can use this file as a requirement file. If conda fails to install all the libraries, use pip to install the missing libraries. https://github.com/sporsho/3D_OutDet/blob/main/wads_8_sep_2023.yml
 
Alternatively, you can also use the below shell script to create the environment. This is a minimal environment, not all the functionalities may be available with it. You can also update the script with any compatible library versions.
 #! /bin/bash  echo "Conda version: " conda -V  echo "Attempting to update conda" yes | conda update conda echo "Creating environment" yes | conda create -n outdet python=3.10 if [ $? -eq 0 ]; then 	echo "basic invironment installed" 	echo "Assuming you are using Bash" 	BASE=$(conda info --base) 	source $BASE/etc/profile.d/conda.sh 	conda activate outdet  	pip config set global.extra-index-url https://pypi.ngc.nvidia.com 	yes | conda install numpy=1.23.1 	yes | conda install cudatoolkit=11.3.1 	yes | conda install pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0 -c pytorch 	yes | pip install pyyaml==6.0 	yes | pip install tqdm==4.46.1 	yes | pip install scikit-image==0.19.3 	yes | pip install scikit-learn==1.1.2 	yes | pip install scipy==1.9.1 	yes | pip install matplotlib==3.6.0 	yes | pip install cubinlinker-cu11==0.3.0.post1 --extra-index-url https://pypi.nvidia.com 	yes | pip install cuda-python==11.8.1 	yes | pip install cudf-cu11==23.6.0 --extra-index-url https://pypi.nvidia.com 	yes | pip install cuml-cu11==23.6.0 --extra-index-url https://pypi.nvidia.com 	yes | pip install cupy-cuda11x==12.1.0  	yes | pip install torch-cluster==1.6.0 	which python  	conda deactivate else	 	echo "environment installation failed" fi

**Comment by sporsho** [comment]
No, there are multiple domain shifts between the datasets hence if you want to use a model trained using wads to infer on snowykitti dataset, you have to apply some fine-tuning with some domain transfer technique. Alternatively, you can do a generalized training. e..g, merge all the training data from snowykitti, wads and spray and train a generalized model. The performance will decrease, but you can apply the learned model on any of the datasets.

**Comment by qq625924821** [comment]
Are there some domain transfer example in you 3D_OutDet project? or could you recommend some relevant materials to me? Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sporsho/3D_OutDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月5日(星期一) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sporsho/3D_OutDet] Need Requirement (Issue #1)





 
No, there are multiple domain shifts between the datasets hence if you want to use a model trained using wads to infer on snowykitti dataset, you have to apply some fine-tuning with some domain transfer technique. Alternatively, you can do a generalized training. e..g, merge all the training data from snowykitti, wads and spray and train a generalized model. The performance will decrease, but you can apply the learned model on any of the datasets.

**Comment by sporsho** [comment]
No, our project is not about domain transfer or adaptation. It is another stream of research and though I did my masters thesis on semi-supervised domain adaptation for MRI images, at present I am not involved with any kind of domain adaptation yet. For starter, you can search on the google scholar e.g., https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=domain+adaptation+point+cloud+segmentation&btnG=

**Comment by qq625924821** [comment]
OK,Thanks! I will try to train it on my datasets.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sporsho/3D_OutDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月5日(星期一) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sporsho/3D_OutDet] Need Requirement (Issue #1)





 
No, there are multiple domain shifts between the datasets hence if you want to use a model trained using wads to infer on snowykitti dataset, you have to apply some fine-tuning with some domain transfer technique. Alternatively, you can do a generalized training. e..g, merge all the training data from snowykitti, wads and spray and train a generalized model. The performance will decrease, but you can apply the learned model on any of the datasets.
