### ISSUE TITLE
Could you provide a more detailed Readme?

### ISSUE THREAD

**Issue by shuaizg** [sporsho/3D_OutDet#2]
Thank you for your excellent work. Could you provide more details on the training and data preparation to help me reproduce it?

**Comment by sporsho** [comment]
Hi, I will try to update the readme next week.

**Comment by shuaizg** [comment]
> Hi, I will try to update the readme next week.

Thanks! lol

**Comment by sporsho** [comment]
Hi, I provided some details in https://github.com/sporsho/3D_OutDet/tree/2-could-you-provide-a-more-detailed-readme 
I will merge the branch after further fine tuning the text. In the meantime, you can get started with the new branch.

**Comment by shuaizg** [comment]
> Hi, I provided some details in https://github.com/sporsho/3D_OutDet/tree/2-could-you-provide-a-more-detailed-readme I will merge the branch after further fine tuning the text. In the meantime, you can get started with the new branch.

Thank you for your reply. This is a detailed instruction.
